### ISSUE TITLE
Mysql database not working

### ISSUE THREAD

**Issue by JuliGame** [Minecraft652/SFTFinance#2]
**Config file:**
IsMysql: true
MysqlUrl: mysql://127.0.0.1:3306/sftfinance
MysqlUser: sv
MysqlPassword: Pass_Here

**MySQL cfg:** 
Database:
![image](https://user-images.githubusercontent.com/60196802/142049473-04c2fb10-c586-433c-a57f-1d7b2bae4d7f.png)

User:
![image](https://user-images.githubusercontent.com/60196802/142049538-7edf868e-4541-40f4-8c52-3073cb43e222.png)
User password is right.

**Error:**
There are no error, I recommend you not to hide errors, it makes it easier to troubleshoot. 
![image](https://user-images.githubusercontent.com/60196802/142049840-6027b41d-af3e-4243-8e3c-f48cb9f5813c.png)
I would write ignored.printStackTrace(); there.

**Comment by Minecraft652** [comment]
I'm sorry this has come up. but this error need to ignored because APILibrary.createWallet is an initialization steps.
Please give me the following points so that I can help solve the problem :
1. Check your sftfinance database table called "wallets" and there if have a CONSOLE wallet.
2. Enter /wallet in the server terminal to check whether it can be displayed normally.
3. If you have any questions "drop database sftfinance" and try again
4. Tell me what's not working and take it further.
Thanks for your issue.
